name: Проверки кода
on:
  push:
    branches: [master]
  pull_request:
    types: [unlabeled, opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    name: Проверки кода
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'WIP') == false && contains(github.event.pull_request.labels.*.name, 'Blocked') == false && contains(github.event.pull_request.labels.*.name, 'Suspended') == false

    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v2

      - name: Установка ноды
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка пакетов
        run: yarn build

      - run: yarn test
        if: always()

      - run: yarn lint
        if: always()
