name: "Size Limit"
on:
  pull_request:
    branches:
      - master
jobs:
  size-limit:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v2

      - name: Установка ноды
        uses: actions/setup-node@v2-beta
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '12.x'
          scope: '@gpn-prototypes'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Проверка size limit
        uses: andresz1/size-limit-action@v1.3.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
